# Generated by Django 5.1.7 on 2025-03-10 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basliq', models.CharField(max_length=200)),
                ('mezmun', models.TextField()),
                ('tarix', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
