# Generated by Django 5.1.7 on 2025-03-11 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='mezmun',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='tarix',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='basliq',
            new_name='title',
        ),
    ]
